package app.views;

import javax.swing.*;
import java.awt.*;

public class TabTest extends JPanel {
    private JPanel TabMenu;
    private JTabbedPane Tab;

    public TabTest() {
        add(Tab);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        TabMenu = new JPanel();
        TabMenu.setLayout(new BorderLayout(0, 0));
        TabMenu.setEnabled(true);
        Tab = new JTabbedPane();
        Tab.setEnabled(true);
        TabMenu.add(Tab, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setForeground(new Color(-5524801));
        Tab.addTab("Accueil", panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Tab.addTab("Ma bibliothéque", panel2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return TabMenu;
    }

}
